### ISSUE TITLE
Getting server error (500)

### ISSUE THREAD

**Issue by baricks** [DOsinga/reverse_image_search#1]
Hi, I'm trying to run an image through the reverse image search engine and have been getting a server error.

**Comment by DOsinga** [comment]
Do you mean on https://douweosinga.com/projects/reverse_image_search ? What image did you try? I think right now it has to be a jpeg, otherwise it will just give a 500. I should probably do something about that.

**Comment by baricks** [comment]
Ah, that was the problem! I was running a png. Thanks, it's a great tool.
